trigger:
  - main

pool:
  name: 'ubuntu' # Your self-hosted agent pool

variables:
  - group: EMA # Variable group with AWS_ACCESS_KEY and AWS_SECRET_KEY

steps:
  - script: |
      echo "Listing files in current directory..."
      ls -R
      echo "Running terraform init with S3 backend..."
      terraform init 
      echo "Running terraform plan..."
      terraform plan -out=tfplan
      echo "Running terraform apply..."
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Init, Plan, Apply'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)